config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  root to: redirect('/welcome',status: 302)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
    respond_to do |format|
      format.html { render :welcome }
    end
  end

  def about
    respond_to do |format|
      format.html { render :about }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<h2>The Authors</h2>

<p>This site was created by Scott Fleming and Katie Bridson.</p>
<p>Back to <%= link_to "welcome", welcome_path %></p>

app/views/static_pages/welcome.html.erb
<%= image_tag "quiz-bubble.png", height: 300 %>
<h1>"Welcome to QuizMe!"</h1>
<p>
   QuizMe is a free <%= link_to "Quizlet","https://quizlet.com", target: "_blank" %> style quizzing application that helps you learn by taking quizzes and trying to improve your scores.
</p>
<h2>Features</h2>

<p>
QuizMe allows users to:
</p>

<ul>
<li>Choose from premade quizzes on a variety of topics</li>
<li>Make your own quizzes to customize your learning</li>
<li>Compare your scores with other users</li>
</ul>

<p>
QuizMe also supports a variety of question styles like multiple choice and fill in the blank.
</p>
<p>
To <%= link_to "about", about_path %>
</p>